import css from '../../starter/styles.css?raw';
import sample from '../../starter/site.json';
import { kitFiles, zipFiles } from '../../starter/core.mjs';
import coreSource from '../../starter/core.mjs?raw';
import generator from '../../starter/generate.mjs?raw';
import readme from '../../starter/README.md?raw';
import deploy from '../../starter/DEPLOY.md?raw';
import ai from '../../starter/CUSTOMIZE_WITH_AI.md?raw';
import license from '../../starter/LICENSE?raw';
import contributing from '../../starter/CONTRIBUTING.md?raw';
import changelog from '../../starter/CHANGELOG.md?raw';
import workflow from '../../starter/.github/workflows/pages.yml?raw';
import packageSource from '../../starter/package.json?raw';
import ignore from '../../starter/.gitignore?raw';
import tests from '../../starter/core.test.mjs?raw';
import notices from '../../starter/THIRD_PARTY_NOTICES.md?raw';
import issue from '../../starter/.github/ISSUE_TEMPLATE/bug_report.md?raw';
export { css, sample };
export const sources = {'THIRD_PARTY_NOTICES.md':notices,'.github/ISSUE_TEMPLATE/bug_report.md':issue,'core.mjs':coreSource,'generate.mjs':generator,'README.md':readme,'DEPLOY.md':deploy,'CUSTOMIZE_WITH_AI.md':ai,'LICENSE':license,'CONTRIBUTING.md':contributing,'CHANGELOG.md':changelog,'.github/workflows/pages.yml':workflow,'package.json':packageSource,'.gitignore':ignore,'core.test.mjs':tests};
export const downloadKit = (site: unknown) => zipFiles(kitFiles(site, css, sources));
