import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import * as m from '../src/lib/dpc-worksheet.mjs';
import * as old from '../src/lib/dpc-worksheet-v4.mjs';
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-6,`${a} != ${b}`);
function costed(){const w=m.newState().worksheet;for(const k of ['extendedSupport','leaveRelief','recruiting','extendedOccupancy'])w.staffing.settings[k]=0;w.values.startupCapital=100000;w.values.openingCash=400000;return w;}
test('trial prices, annual discount and salary/bonus economics reconcile',()=>{
 const w=costed(),a=m.calculateWorksheet(w);assert.equal(a.coreAnnual,2400);assert.equal(a.extendedAnnual,3360);assert.equal(a.safeMembers,384);assert.equal(a.revenue,1263600);assert.equal(a.physicianBasePay,480000);assert.equal(a.enteredBaseCost,846000);assert.equal(a.incentiveCost,83520);assert.equal(a.incentiveCash,69600);assert.equal(a.bonusPerAssociate,34800);assert.equal(a.surplus,334080);near(a.incentiveCash+a.incentiveBurden,a.incentiveCost);near(a.revenue-a.costs,a.surplus);
 w.values.prepayShare=100;const b=m.calculateWorksheet(w);assert.equal(b.revenue,1123200);assert.equal(b.bonusPerAssociate,23100);assert.equal(b.surplus,221760);assert.equal(b.targetMembers,334);
});
test('target membership includes incentives and is the first whole-member crossing',()=>{for(const share of [0,50,100]){const w=costed();w.values.prepayShare=share;w.staffing.enrollmentMode='stress';const a=m.calculateWorksheet(w);w.values.members=a.targetMembers;assert.ok(m.calculateWorksheet(w).margin>=15);w.values.members=a.targetMembers-1;assert.ok(m.calculateWorksheet(w).margin<15);}});
test('ancillary sales cannot increase the pool; direct costs are counted',()=>{const w=costed(),a=m.calculateWorksheet(w);w.customRows.push({...m.blankRow('labs-income'),label:'Lab receipts',value:50000,unit:'USD',treatment:'practice_annual_revenue'});let b=m.calculateWorksheet(w);near(b.incentiveCost,a.incentiveCost);near(b.surplus,a.surplus+50000);w.customRows.push({...m.blankRow('labs-cost'),value:30000,unit:'USD',treatment:'practice_annual_cost'});b=m.calculateWorksheet(w);near(b.costsBeforeIncentives,a.costsBeforeIncentives+30000);near(b.incentiveCost,a.incentiveCost-6000);});
test('hurdles, quality conditions, missing inputs and unprofitable practice control awards',()=>{const w=costed();w.staffing.incentives.annualHurdle=100000;assert.equal(m.calculateWorksheet(w).incentiveCost,63520);w.staffing.incentives.qualityPercent=50;assert.equal(m.calculateWorksheet(w).incentiveCost,31760);w.staffing.incentives.qualityPercent=0;assert.equal(m.calculateWorksheet(w).incentiveCost,0);w.staffing.incentives.qualityPercent=null;assert.equal(m.calculateWorksheet(w).surplus,null);w.staffing.incentives.qualityPercent=100;w.values.members=1;assert.equal(m.calculateWorksheet(w).incentiveCost,0);assert.equal(m.calculateWorksheet(m.newState().worksheet).incentiveCost,71520);});
test('monthly bonuses use earned membership revenue, reconcile cash, and exclude owner-only months',()=>{const w=costed();w.values.prepayShare=100;const l=m.calculateLaunchWorksheet(w);let cash=w.values.openingCash,deferred=0,totalBonus=0;for(const r of l.rows){near(r.costs,r.costsBeforeIncentives+r.incentiveCost);near(r.operatingResult,r.revenue-r.costs);cash+=r.receipts-r.costs-r.debtPayment-r.startupSpend+r.financing;near(r.cashBalance,cash);near(deferred+r.receipts-r.revenue,r.deferredRevenue);deferred=r.deferredRevenue;totalBonus+=r.incentiveCost;if(r.month<5)assert.equal(r.incentiveCost,0);}assert.ok(totalBonus>0);near(l.totalOperatingResult,l.rows.at(-1).cumulativeOperating);});
test('R05 imports retain every original input and all financial results',()=>{const s=old.newState();s.worksheet.name='Earlier review';for(const k of ['extendedSupport','leaveRelief','recruiting','extendedOccupancy'])s.worksheet.staffing.settings[k]=0;s.worksheet.values.corePrice=285;s.feedback='Keep me';const upgraded=m.validateState(s);assert.deepEqual(upgraded.worksheet.values,s.worksheet.values);assert.deepEqual(upgraded.worksheet.staffing.roles,s.worksheet.staffing.roles);assert.equal(upgraded.worksheet.staffing.incentives,null);for(const key of ['surplus','revenue','costs','physicianPay','breakEvenMembers','targetMembers'])near(m.calculateWorksheet(upgraded.worksheet)[key],old.calculateWorksheet(s.worksheet)[key]);near(m.calculateLaunchWorksheet(upgraded.worksheet).totalOperatingResult,old.calculateLaunchWorksheet(s.worksheet).totalOperatingResult);const next=m.startRevised(upgraded);assert.equal(next.worksheet.values.corePrice,250);assert.equal(next.preservedWorksheets[0].values.corePrice,285);assert.equal(next.feedback,'Keep me');});
test('profit-share exports roundtrip and reject malformed assumptions',()=>{const s=m.newState();s.worksheet.staffing.incentives.poolPercent=15;const p=m.exportPack(s);assert.deepEqual(m.validateState(JSON.parse(JSON.stringify(p))),s);assert.match(m.worksheetCsv(s),/Share of eligible operating surplus/);assert.match(m.reviewText(s),/Gross bonus per eligible associate/);p.worksheet.staffing.incentives.poolPercent=101;assert.throws(()=>m.validateState(p));});
test('R06 snapshot, PDF revision and model are aligned',()=>{const d=JSON.parse(fs.readFileSync(new URL('../docs/dpc/reference-results-r06.json',import.meta.url))),r=JSON.parse(fs.readFileSync(new URL('../src/data/dpc-revisions.json',import.meta.url)));assert.deepEqual(d.revision,r);assert.equal(r.modelVersion,m.MODEL_VERSION);const a=m.calculateWorksheet(d.state.worksheet);for(const key of ['safeMembers','revenue','enteredBaseCost','surplusBeforeCoverage'])near(d.mature[key],a[key]);});
